# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-17 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=20)),
                ('pcost', models.IntegerField()),
                ('pcolor', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('pclass', models.CharField(max_length=20)),
                ('pmdate', models.DateTimeField()),
                ('pedate', models.DateTimeField()),
            ],
        ),
    ]
